### ISSUE TITLE
Why are there dependencies in GitHub ci, e.g. for TYPO3-Continuous-Integration/TYPO3-CI-PHP-CS-Fixer

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/tea#256]
locallly, I can just run the command

`composer ci:php:cs-fixer`

but in .github/workflows/ci.yaml:

```
php-cs-fixer:    
  name: "PHP CS Fixer"    
  runs-on: ubuntu-20.04    
  needs: php-lint    
  steps:      
    - name: "Checkout"        
      uses: actions/checkout@v2      
    - name: "Run PHP CS Fixer"        
    uses: TYPO3-Continuous-Integration/TYPO3-CI-PHP-CS-Fixer@v1
```

For me - `as a user who wants to understand more or less how it works and why we do things the way we do them, but is not an expert` - it would be great if things were kept as simple and consistent as possible.

Having the extra dependency on `Continuous-Integration/TYPO3-CI-PHP-CS-Fixer` is an extra level of abstraction. Also the README on that does not make it self-explanatory to me.

You already have the commands in composer.json. Why not use them in the GitHub CI?

For example, for the linter, you do this:

```
- name: "Run PHP lint"        
run: "composer ci:php:lint"
```

So, this seems a little inconsistent to me.
