### ISSUE TITLE
Restructure the CI steps using a command matrix

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#63]
Currently, we have the same steps over and over in the `ci.yml` for `typoscript-lint` and `php-code-sniffer`. And this will get worse with each checker step we add.

To reduce duplication, I propose we consistently use Composer scripts for the CI checks. This will allow us to use a [matrix for the different commands](https://github.com/MyIntervals/emogrifier/blob/master/.github/workflows/ci.yml#L67) like this (maybe with a different prefix to the Composer commands as we use more than just PHP-related checks):

```yaml
    strategy:
      matrix:
        command:
          - fixer
          - md
          - psalm
          - sniff
…
      - name: Run Command
        run: composer ci:php:${{ matrix.command }}
```

@lukaszuznanski What do you think?
